"""empty message

Revision ID: 67c9787c8da4
Revises: d973781901f1
Create Date: 2022-08-17 21:57:17.247034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67c9787c8da4'
down_revision = 'd973781901f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('live_matches', sa.Column('fen', sa.String(length=128), server_default = "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('live_matches', 'fen')
    # ### end Alembic commands ###
